name: Frontend Lint + Autofix

on:
  push: {}
  pull_request: {}

jobs:
  lint-frontend:
    name: "⚛️ Frontend: ESLint + Prettier (Auto-Fix)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint (auto-fix)
        working-directory: frontend
        run: npm run lint:fix

      - name: Run Prettier (auto-fix)
        working-directory: frontend
        run: npm run format:fix

      - name: Show diff after auto-fix
        run: git diff || true
