
name: MongoDB Backup

on:
  workflow_dispatch:   # manueller Start über Actions
  schedule:
    - cron: "0 2 * * *"   # jeden Tag um 2:00 Uhr nachts

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install MongoDB tools
        run: |
          curl -OL https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.12.2.tgz
          tar -xvf mongodb-database-tools-ubuntu2204-x86_64-100.12.2.tgz
          sudo mv mongodb-database-tools-*/bin/* /usr/local/bin/
          mongodump --version
          bsondump --version
          
      - name: Run mongodump
        run: |
          mkdir -p backups
          mongodump --uri="$MONGO_URI" --db=job_database --out=./backups/mongo-$(date +'%Y-%m-%d_%H-%M') --verbose
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Convert BSON to JSON
        run: |
          DUMP_DIR=$(find ./backups -type d -name job_database)
          for file in $(find "$DUMP_DIR" -name "*.bson"); do
          base=$(basename "$file" .bson)
          bsondump "$file" > "./backups/${base}.json"
          echo "Exported $file -> backups/${base}.json"
          done


      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: mongo-backup
          path: backups
          retention-days: 7
