
name: MongoDB Backup

on:
  workflow_dispatch:   # manueller Start über Actions
  schedule:
    - cron: "0 2 * * *"   # jeden Tag um 2:00 Uhr nachts

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install MongoDB tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Run mongodump
        run: |
          mkdir -p backups
          mongodump --uri="$MONGO_URI" --db=job_database --out=./backups/mongo-$(date +'%Y-%m-%d_%H-%M') --verbose
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Convert BSON to JSON
        run: |
          for file in $(find ./backups -name "*.bson"); do
            base=$(basename "$file" .bson)
            bsondump "$file" > "./backups/${base}.json"
          done

      - name: Upload backup artifact
        uses: actions/upload-artifact@v3
        with:
          name: mongo-backup
          path: backups
          retention-days: 7
